version: '3'
services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8001:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: somepassword
    volumes:
      - './:/var/www/html'
  db:
    image: "mysql:5.7.22"
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
    driver: local
